
const responses = [
    { question: 'Tell me about yourself', answer: 'Charles Dave Reyes is a graduate from the University of Santo Tomas with the degree in Bachelor of Science in Information Technology. He describes himself as an ambitious and passionate person who is eager to learn and grow in the field of Information Technology. He is also a perfectionist, who loves to hone his crafts and pay attention to small details.' },
    { question: 'Can you tell me about yourself', answer: 'Charles Dave Reyes is a graduate from the University of Santo Tomas with the degree in Bachelor of Science in Information Technology. He describes himself as an ambitious and passionate person who is eager to learn and grow in the field of Information Technology. He is also a perfectionist, who loves to hone his crafts and pay attention to small details.' },
    { question: 'Can you tell me more about yourself', answer: 'Charles Dave Reyes is a graduate from the University of Santo Tomas with the degree in Bachelor of Science in Information Technology. He describes himself as an ambitious and passionate person who is eager to learn and grow in the field of Information Technology. He is also a perfectionist, who loves to hone his crafts and pay attention to small details.' },
    { question: 'Can you introduce yourself?', answer: 'Charles Dave Reyes is a graduate from the University of Santo Tomas with the degree in Bachelor of Science in Information Technology. He describes himself as an ambitious and passionate person who is eager to learn and grow in the field of Information Technology. He is also a perfectionist, who loves to hone his crafts and pay attention to small details.' },
    { question: 'What can you share about yourself', answer: 'Charles Dave Reyes is a graduate from the University of Santo Tomas with the degree in Bachelor of Science in Information Technology. He describes himself as an ambitious and passionate person who is eager to learn and grow in the field of Information Technology. He is also a perfectionist, who loves to hone his crafts and pay attention to small details.' },
    { question: 'I\'d like to know more about you.', answer: 'Charles Dave Reyes is a graduate from the University of Santo Tomas with the degree in Bachelor of Science in Information Technology. He describes himself as an ambitious and passionate person who is eager to learn and grow in the field of Information Technology. He is also a perfectionist, who loves to hone his crafts and pay attention to small details.' },
    { question: 'Can you describe yourself?.', answer: 'Charles Dave Reyes is a graduate from the University of Santo Tomas with the degree in Bachelor of Science in Information Technology. He describes himself as an ambitious and passionate person who is eager to learn and grow in the field of Information Technology. He is also a perfectionist, who loves to hone his crafts and pay attention to small details.' },
    { question: 'How would you describe yourself?.', answer: 'Charles Dave Reyes is a graduate from the University of Santo Tomas with the degree in Bachelor of Science in Information Technology. He describes himself as an ambitious and passionate person who is eager to learn and grow in the field of Information Technology. He is also a perfectionist, who loves to hone his crafts and pay attention to small details.' },
    { question: 'What can you say about yourself?.', answer: 'Charles Dave Reyes is a graduate from the University of Santo Tomas with the degree in Bachelor of Science in Information Technology. He describes himself as an ambitious and passionate person who is eager to learn and grow in the field of Information Technology. He is also a perfectionist, who loves to hone his crafts and pay attention to small details.' },
    { question: 'Could you tell me about your background?.', answer: 'Charles Dave Reyes is a graduate from the University of Santo Tomas with the degree in Bachelor of Science in Information Technology. He describes himself as an ambitious and passionate person who is eager to learn and grow in the field of Information Technology. He is also a perfectionist, who loves to hone his crafts and pay attention to small details.' },
    { question: 'I\'d love to hear more about you.', answer: 'Charles Dave Reyes is a graduate from the University of Santo Tomas with the degree in Bachelor of Science in Information Technology. He describes himself as an ambitious and passionate person who is eager to learn and grow in the field of Information Technology. He is also a perfectionist, who loves to hone his crafts and pay attention to small details.' },
    { question: 'Tell me a little bit about yourself.', answer: 'Charles Dave Reyes is a graduate from the University of Santo Tomas with the degree in Bachelor of Science in Information Technology. He describes himself as an ambitious and passionate person who is eager to learn and grow in the field of Information Technology. He is also a perfectionist, who loves to hone his crafts and pay attention to small details.' },
    { question: 'Can you share some details about yourself?', answer: 'Charles Dave Reyes is a graduate from the University of Santo Tomas with the degree in Bachelor of Science in Information Technology. He describes himself as an ambitious and passionate person who is eager to learn and grow in the field of Information Technology. He is also a perfectionist, who loves to hone his crafts and pay attention to small details.' },
    { question: 'Can you tell more about Charles Dave Reyes?', answer: 'Charles Dave Reyes is a graduate from the University of Santo Tomas with the degree in Bachelor of Science in Information Technology. He describes himself as an ambitious and passionate person who is eager to learn and grow in the field of Information Technology. He is also a perfectionist, who loves to hone his crafts and pay attention to small details.' },
    
    

    { question: 'How old is he?', answer: 'As of 2024, he is currently 22 years old.' },
    { question: 'How old is Charles Dave Reyes?', answer: 'As of 2024, he is currently 22 years old.' },
    { question: 'How old is Charles?', answer: 'As of 2024, he is currently 22 years old.' },
    { question: 'How old are you?', answer: 'As of 2024, he is currently 22 years old.' },
    { question: 'When is his birthday?', answer: 'May 18, 2002' },
    { question: 'Where does he live?', answer: 'He is currently residing in San Mateo Rizal, Philippines.' },
    { question: 'Where did you graduate?', answer: 'Charles Dave Reyes graduated from the University of Santo Tomas in Manila, Philippines.' },
    { question: 'Where did you graduate college?', answer: 'Charles Dave Reyes graduated from the University of Santo Tomas in Manila, Philippines.' },
    { question: 'When did you graduate?', answer: 'Charles Dave Reyes graduated from the University of Santo Tomas on the year of 2024.' },
    { question: 'What year did you graduate?', answer: 'Charles Dave Reyes graduated from the University of Santo Tomas on the year of 2024.' },



    { question: 'What role are you most comfortable at?', answer: 'Charles is comfortable working with any role, but out of all them, he is the most efficient with software engineering'},
    { question: 'What are your soft skills?', answer: 'Charles is a strong analytical and problem solving individual who loves to take on challenges and its opportunities. He also excels with collaborating with other people and working together as a team to achieve a certain goal' },
    { question: 'Who are you?', answer: 'Charles Dave Reyes is a software engineer with years of experience in developing websites' },
    { question: 'Who is Charles Dave Reyes?', answer: 'Charles Dave Reyes is a seasoned software engineer with extensive experience in website development, quality assurance testing, design, and infrastracture.' },
    { question: 'Who is Charles?', answer: 'Charles Dave Reyes is a seasoned software engineer with extensive experience in website development, quality assurance testing, design, and infrastracture.' },
    { question: 'Who is Dave?', answer: 'Charles Dave Reyes is a seasoned software engineer with extensive experience in website development, quality assurance testing, design, and infrastracture.' },
    { question: 'Who is Reyes?', answer: 'Charles Dave Reyes is a seasoned software engineer with extensive experience in website development, quality assurance testing, design, and infrastracture.' },
    { question: 'Who is Mr. Reyes?', answer: 'Charles Dave Reyes is a seasoned software engineer with extensive experience in website development, quality assurance testing, design, and infrastracture.' },

    { question: 'Who is he?', answer: 'Charles Dave Reyes is a seasoned software engineer with extensive experience in website development, quality assurance testing, design, and infrastracture.'},
    { question: 'What is your preferred name?', answer: 'Feel free to call me with whatever your heart desires, but you could just call me Charles' },
    { question: 'Where do you currently live?', answer: 'I am based in San Mateo Rizal, Philippines' },
    { question: 'Where do you live?', answer: 'I am based in San Mateo Rizal, Philippines' },
    { question: 'Where do you currently reside?', answer: 'I am based in San Mateo Rizal, Philippines' },
    { question: 'Where do you reside?', answer: 'I am based in San Mateo Rizal, Philippines' },
    { question: 'Where are you located?', answer: 'I am based in San Mateo Rizal, Philippines' },
    { question: 'Do you watch anime?', answer: 'Yes, some of his favorites are Naruto, One Piece, and Jujutsu Kaisen' },
    { question: 'Do you like travelling?', answer: 'Yes, he loves to travel to different places and explore new cultures and perspectives' },
    { question: 'Who am I talking to?', answer: 'BotFolio is a chatbot created to help the audience learn more about the author of the website.' },
    { question: 'Where did he study in college?', answer: 'Charles graduated from the University of Santo Tomas with the degree of Bachelor of Science in Information Technology' },
    { question: 'Where did you study in college?', answer: 'Charles graduated from the University of Santo Tomas with the degree of Bachelor of Science in Information Technology' },
    { question: 'What are your plans in the future?', answer: 'In the future, Charles plans to improve and learn more about the concepts of technology and how he could make an impact in the industry. He also plans on taking certification exams to boost his overall ability and reliability.' },
    
    { question: 'Are you a software engineer?', answer: 'Yes, Charles Dave Reyes is a software engineer' },
    { question: 'Can you work as a software engineer?', answer: 'Yes, software engineering is a role he is really passionate about and looks forward in the future.' },
    { question: 'Do you have any experience in ServiceNow?', answer: 'During internship, Charles was able to gain valuable experience and practical solutions in ServiceNow.' },
    { question: 'ServiceNow', answer: 'During internship, Charles was able to gain valuable experience and practical solutions in ServiceNow.' },
    { question: 'What is Thirdera?', answer: 'Thirdera is a company that specialized in utilizing ServiceNow platform to provide seamless experience to their users. Charles was a former intern of the company who gained valuable experience along with his friends' },
    { question: 'Tell me about your internship experience?', answer: 'The internship experience of the author was definitely a fun rollercoaster ride, while he did made lots of mistakes, he was able to improve from those various experiences. During this time, I was able to learn the core concepts of Javascript and apply it in the ServiceNow platform.' },
    { question: 'What are your strengths?', answer: 'Charles is known to have great amount of resilience and adaptability. He believed that he would not be able to make it this far without this characteristic that he is constantly honing. He is also great at cooperating and working with other individuals through teamwork as reflected by his roles and experiences throughout his journey.' },
    { question: 'What are your weaknesses?', answer: 'As a perfectionist, he is very overcritical about himself and always tries to improve in any way possible. However, it can also be a double-edged sword as he sometimes struggle with time management and also with himself.' },
    { question: 'What is his strengths?', answer: 'Charles is known to have great amount of resilience and adaptability. He believed that he would not be able to make it this far without this characteristic that he is constantly honing. He is also great at cooperating and working with other individuals through teamwork as reflected by his roles and experiences throughout his journey.' },
    { question: 'What is his weaknesses?', answer: 'As a perfectionist, he is very overcritical about himself and always tries to improve in any way possible. However, it can also be a double-edged sword as he sometimes struggle with time management and also with himself.' },
    { question: 'What is his strengths and weaknesses?', answer: 'Charles is known to have great amount of resilience and adaptability. He believed that he would not be able to make it this far without this characteristic that he is constantly honing. He is also great at cooperating and working with other individuals through teamwork as reflected by his roles and experiences throughout his journey. However, as a perfectionist he is very overcritical about himself and always tries to improve in any way possible. However, it can also be a double-edged sword as he sometimes struggle with time management and also with himself.' },
    { question: 'What are his strengths and weaknesses?', answer: 'Charles is known to have great amount of resilience and adaptability. He believed that he would not be able to make it this far without this characteristic that he is constantly honing. He is also great at cooperating and working with other individuals through teamwork as reflected by his roles and experiences throughout his journey. However, as a perfectionist he is very overcritical about himself and always tries to improve in any way possible. However, it can also be a double-edged sword as he sometimes struggle with time management and also with himself.' },
    { question: 'What are your strengths?', answer: 'Charles is known to have great amount of resilience and adaptability. He believed that he would not be able to make it this far without this characteristic that he is constantly honing. He is also great at cooperating and working with other individuals through teamwork as reflected by his roles and experiences throughout his journey.' },
    { question: 'What are your weaknesses?', answer: 'As a perfectionist, he is very overcritical about himself and always tries to improve in any way possible. However, it can also be a double-edged sword as he sometimes struggle with time management and also with himself. ' },
    { question: 'Tell me about his strengths?', answer: 'Charles is known to have great amount of resilience and adaptability. He believed that he would not be able to make it this far without this characteristic that he is constantly honing. He is also great at cooperating and working with other individuals through teamwork as reflected by his roles and experiences throughout his journey.' },
    { question: 'Tell me about his weaknesses?', answer: 'As a perfectionist, he is very overcritical about himself and always tries to improve in any way possible. However, it can also be a double-edged sword as he sometimes struggle with time management and also with himself. ' },
    
    { question: 'Who is Charles Dave Reyes?', answer: 'Charles Dave Reyes is a software engineer with years of experience in developing websites' },
    { question: 'Who am I talking to?', answer: 'BotFolio is a chatbot created to help the audience learn more about the author of the website.' },
    { question: 'What are you?', answer: 'BotFolio is a chatbot created to help the audience learn more about the author of the website.' },
    { question: 'Why did you create this website?', answer: 'Charles Dave Reyes developed this website as a platform to introduce himself to his audience, showcase his expertise, and connect with industry professionals.' },
    { question: 'Why did you develop this website?', answer: 'Charles Dave Reyes developed this website as a platform to introduce himself to his audience, showcase his expertise, and connect with industry professionals.' },
    { question: 'Why did you make this website?', answer: 'Charles Dave Reyes developed this website as a platform to introduce himself to his audience, showcase his expertise, and connect with industry professionals.' },
    

    { question: 'What is your mobile number?', answer: 'Feel free to contact me via phone at 09491163935.' },
    { question: 'Provide me your mobile number?', answer: 'Sure, feel free to contact me via phone at 09491163935.' },
    { question: 'Can you give me your phone number?', answer: 'Sure, feel free to contact me via phone at 09491163935.' },
    { question: 'Provide me your mobile number?', answer: 'Sure, feel free to contact me via phone at 09491163935.' },
    { question: 'Could you share your mobile number?', answer: 'Sure, feel free to contact me via phone at 09491163935.' },
    { question: 'May I have your phone number?', answer: 'Sure, feel free to contact me via phone at 09491163935.' },


    { question: 'hatdog?', answer: 'hatdog ka rin' },
    { question: 'shawarma', answer: 'shawarma who?' },
    { question: 'shawarma rice', answer: 'shawarma who?' },
    { question: 'test', answer: 'I know who you are 😉' },
    { question: 'testtest', answer: 'I know who you are 😉' },
    { question: 'ganda ni iu', answer: 'I know who you are 😉' },
    { question: 'What should I do?', answer: 'Please feel free to ask me any questions about the author.' },
    { question: 'What is this website?', answer: 'This website is designed to learn more about the author named Charles Dave Reyes.' },
    { question: 'What is the goal of the website?', answer: 'This website is designed to learn more about the author named Charles Dave Reyes.' },
    { question: 'Botfolio', answer: 'BotFolio is a chatbot created to help the audience learn more about the author of the website.' },
    { question: 'Can I hire you?', answer: 'Sure, please feel free to contact me at your earliest convenience!' },
    { question: 'What is Botfolio?', answer: 'BotFolio is a chatbot created to help the audience learn more about the author of the website.' },
    { question: 'Did he create this website', answer: 'Charles Dave Reyes is the creator of this website.' },
    { question: 'Who created this website?', answer: 'Charles Dave Reyes is the creator of this website.' },
    { question: 'Hello World!', answer: 'Hello Universe!' },
    { question: 'Hello', answer: 'Hi, how can I help you?' },
    { question: 'Hi', answer: 'Hi, how can I help you?' },
    { question: 'Hey!', answer: 'Hi, how can I help you?' },
    { question: 'Hey there!', answer: 'Hi, how can I help you?' },
    { question: 'Good morning!', answer: 'Hi, how can I help you?' },
    { question: 'Good afternoon!', answer: 'Hi, how can I help you?' },
    { question: 'Good evening!', answer: 'Hi, how can I help you?' },
    

    { question: 'Are you single?', answer: 'I am currently single with no one to mingle.' },

    { question: 'Do you have any experience in React?', answer: 'Yes, Charles is knowledgeable and versatile with the React Framework.' },
    { question: 'What programming languages are you familiar with?', answer: 'Charles Dave Reyes specializes on utilizing Vanilla Javascript and frameworks such as React and Vue. He is also proficient with other programming languages such as Python, PHP (Laravel), C# (Asp.net), Java and more!' },
    { question: 'Do have you any experience with Javascript?', answer: 'Yes, Vanilla Javascript and frameworks (React, Vue, Angular).' },
    { question: 'Can you explain what a RESTful API is?', answer: 'A RESTful API is an architectural style for designing networked applications. It uses standard HTTP methods (GET, POST, PUT, DELETE) and provides a way for systems to communicate over the web by using URLs and JSON or XML for data interchange.' },
    { question: 'How do you ensure code quality and maintainability?', answer: 'I ensure code quality by adhering to coding standards, performing code reviews, and writing clean, modular code. I also use tools like linters and formatters to maintain consistency and follow best practices for documentation and testing.' },
    { question: 'What is your experience with frontend frameworks?', answer: 'I am a seasoned frontend engineer with a strong foundation in developing intricate front-end logic. My expertise lies in harnessing the capabilities of frameworks such as React, Laravel, and ASP.NET to craft exceptional user experiences.' },
    { question: 'Frontend frameworks?', answer: 'I am a seasoned frontend engineer with a strong foundation in developing intricate front-end logic. My expertise lies in harnessing the capabilities of frameworks such as React, Laravel, and ASP.NET to craft exceptional user experiences.' },
    { question: 'What is your experience with backend frameworks?', answer: 'I am a proficient backend engineer with a proven track record of developing the logic and infrastracture of the applications. My expertise includes managing databases, API development, server-side logic and solutions utilizing MySQL and Firebase. ' },
    { question: 'Backend frameworks?', answer: 'I am a proficient backend engineer with a proven track record of developing the logic and infrastracture of the applications. My expertise includes managing databases, API development, server-side logic and solutions utilizing MySQL and Firebase. ' },


    { question: 'What is a software engineer?', answer: 'A software engineer is a professional who applies engineering methodologies to the conception, creation, testing, and ongoing management of software applications.' },
    { question: 'What is a quality assurance specialist?', answer: 'A Quality Assurance Specialist is a professional who ensures that products or services meet the highest quality standards. They focus on preventing defects and errors by implementing quality control measures throughout the development process. ' },
    { question: 'What is a full stack developer', answer: 'A full-stack developer is a professional capable of handling both the front-end and back-end aspects of software development. They specialize in the development of high-performance application.' },
    { question: 'What is an UI / UX Designer?', answer: 'A UI/UX Designer is a professional who focuses on enhancing user experiences through design.' },
    { question: 'What is an AI / ML Specialist?', answer: ' An AI/ML Engineer is a professional who develops intelligent systems by applying machine learning algorithms and techniques. They combine expertise in computer science, mathematics, and statistics to create models that can learn from data and make predictions or decisions.' },
    { question: 'What is UI / UX Designer?', answer: 'A UI/UX Designer is a professional who focuses on enhancing user experiences through design.' },
    { question: 'What is AI / ML Specialist?', answer: ' An AI/ML Engineer is a professional who develops intelligent systems by applying machine learning algorithms and techniques. They combine expertise in computer science, mathematics, and statistics to create models that can learn from data and make predictions or decisions.' },
    { question: 'What is an Photographer?', answer: 'A photographer is a visual storyteller who captures and creates images using a camera.' },
    { question: 'What is a project manager?', answer: 'A project manager is a professional who plans, executes, and closes projects. They manage teams, resources, and timelines to ensure projects are completed successfully.'},
    { question: 'What does a software engineer do?', answer: 'A software engineer is a professional who applies engineering methodologies to the conception, creation, testing, and ongoing management of software applications.' },
    { question: 'What does a quality assurance specialist do?', answer: 'A Quality Assurance Specialist is a professional who ensures that products or services meet the highest quality standards. They focus on preventing defects and errors by implementing quality control measures throughout the development process. ' },
    { question: 'What does a full stack developer do', answer: 'A full-stack developer is a professional capable of handling both the front-end and back-end aspects of software development. They specialize in the development of high-performance application.' },
    { question: 'What does an UI / UX Designer do?', answer: 'A UI/UX Designer is a professional who focuses on enhancing user experiences through design.' },
    { question: 'What does an AI / ML Specialist do?', answer: ' An AI/ML Engineer is a professional who develops intelligent systems by applying machine learning algorithms and techniques. They combine expertise in computer science, mathematics, and statistics to create models that can learn from data and make predictions or decisions.' },
    { question: 'What does an UI / UX Designer do?', answer: 'A UI/UX Designer is a professional who focuses on enhancing user experiences through design.' },
    { question: 'What does an AI / ML Specialist do?', answer: ' An AI/ML Engineer is a professional who develops intelligent systems by applying machine learning algorithms and techniques. They combine expertise in computer science, mathematics, and statistics to create models that can learn from data and make predictions or decisions.' },
    { question: 'What does an Photographer do?', answer: 'A photographer is a visual storyteller who captures and creates images using a camera.' },
    { question: 'What does a project manager do?', answer: 'A project manager is a professional who plans, executes, and closes projects. They manage teams, resources, and timelines to ensure projects are completed successfully.'},


    { question: 'Can you explain the concept of MVC architecture?', answer: 'MVC (Model-View-Controller) is an architectural pattern used for designing web applications. The Model represents the data and business logic, the View is responsible for rendering the UI, and the Controller handles user input and updates the Model and View accordingly.' },

    { question: 'Can you explain the concept of MVC architecture?', answer: 'MVC (Model-View-Controller) is an architectural pattern used for designing web applications. The Model represents the data and business logic, the View is responsible for rendering the UI, and the Controller handles user input and updates the Model and View accordingly.' },
    { question: 'What is the MVC architecture?', answer: 'MVC (Model-View-Controller) is an architectural pattern used for designing web applications. The Model represents the data and business logic, the View is responsible for rendering the UI, and the Controller handles user input and updates the Model and View accordingly.' },
    { question: 'What strategies do you use for effective team collaboration?', answer: 'I use strategies such as regular team meetings, clear communication, and collaborative tools (like Zoom or Teams) to ensure effective collaboration. I also focus on setting clear goals and providing constructive feedback to enhance team productivity.' },

    { question: 'Did you develop Handa Bata', answer: 'Yes, Charles served as the project manager of Handa Bata and developed the website along with his friends.' },
    { question: 'Are you the project manager of Handa Bata', answer: 'Yes, Charles served as the project manager of Handa Bata and developed the website along with his friends' },
    { question: 'Handa Bata', answer: 'Handa Bata is a web and mobile application that aims to improve the earthquake and typhoon preparedness and awareness of children with pixelized and gamified elements to provide a strong interest to its audience' },
    { question: 'When is your birthday?', answer: 'May 18, 2002' },
    { question: 'How are you?', answer: 'Hi, how can I help you?' },
    { question: 'HAHAHAHA?', answer: 'I\m glad your enjoying yourself <33' },
    { question: 'Are you better than ChatGPT?', answer: 'Please don\'t compare me with other AI platforms.'},
    { question: 'Are you better than Bard?', answer: 'Please don\'t compare me with other AI platforms.'},
    { question: 'But would you lose?' , answer: 'Nah, I\'d win'},
    { question: 'Would you lose?' , answer: 'Nah, I\'d win'},
    { question: 'Who\'s stronger? Him or you?' , answer: 'Well if he regained all his power, he might cause me a little trouble.'},
    { question: 'Him or you?' , answer: 'Well if he regained all his power, he might cause me a little trouble.'},
    { question: 'Nah, I\'d win' , answer: 'Keep on dreamin'},
    { question: 'Nahh' , answer: '...'},
    { question: ' Hi, how\'s it going?' , answer: 'Hi, how can I help you?'},
    { question: 'Hi!' , answer: 'Hi, how can I help you?'},
    { question: 'Hi.' , answer: 'Hi, how can I help you?'},
    { question: 'Hi?' , answer: 'Hi, how can I help you?'},
    { question: 'Hi there.' , answer: 'Hi, how can I help you?'},
    { question: 'Hello there?' , answer: 'Hi, how can I help you?'},
    { question: 'What are your hobbies?' , answer: 'Charles loves to play badminton and listen to some music on his free time.'},
    { question: 'Do you play any sports?' , answer: 'Charles possesses a keen interest in athletic pursuits, excelling in both badminton and table tennis. Moreover, he engages in casual play of volleyball and chess.'},
    
    
    

    
    
];

export default responses;